In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("titanic_dataset.csv")

In [ ]:
df.head()

In [ ]:
df.describe()

In [ ]:
df.shape

In [6]:
features=np.array(df.drop(['survived'],axis=1))

In [7]:
features

array([[3, 22.0, 1, ..., 0, 0, 1],
       [1, 38.0, 1, ..., 1, 0, 0],
       [3, 26.0, 0, ..., 0, 0, 1],
       ...,
       [3, 29.69911764705882, 1, ..., 0, 0, 1],
       [1, 26.0, 0, ..., 1, 0, 0],
       [3, 32.0, 0, ..., 0, 1, 0]], dtype=object)

In [8]:
n_cols = features.shape[1]
n_cols

10

In [9]:
target=df["survived"]

In [10]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(features,target,test_size=0.3,random_state=101)

In [12]:
from keras.utils import to_categorical

Using TensorFlow backend.
C:\Users\User\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\User\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\User\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\User\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526

In [13]:
target=to_categorical(target)
target

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [14]:
y_train=to_categorical(y_train)
y_train

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [15]:
y_test=to_categorical(y_test)
y_test

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.

In [33]:
import keras
from keras.layers import Dense
from keras.models import Sequential


In [22]:
model = Sequential()

In [23]:
model.add(Dense(100,activation='relu',input_shape=(10,)))

In [24]:
model.add(Dense(100, activation='relu'))

model.add(Dense(2,activation='softmax'))


In [25]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [31]:
model.fit(features,target,validation_split=0.3,epochs=10,batch_size=128)

Train on 623 samples, validate on 268 samples
Epoch 1/10
623/623 [==============================] - 0s 33us/step - loss: 0.4769 - accuracy: 0.7913 - val_loss: 0.4307 - val_accuracy: 0.8097
Epoch 2/10
623/623 [==============================] - 0s 21us/step - loss: 0.4763 - accuracy: 0.7817 - val_loss: 0.4826 - val_accuracy: 0.7649
Epoch 3/10
623/623 [==============================] - 0s 28us/step - loss: 0.4855 - accuracy: 0.7785 - val_loss: 0.4322 - val_accuracy: 0.8097
Epoch 4/10
623/623 [==============================] - 0s 28us/step - loss: 0.4792 - accuracy: 0.7897 - val_loss: 0.4514 - val_accuracy: 0.7799
Epoch 5/10
623/623 [==============================] - 0s 26us/step - loss: 0.4834 - accuracy: 0.7737 - val_loss: 0.4347 - val_accuracy: 0.8209
Epoch 6/10
623/623 [==============================] - 0s 30us/step - loss: 0.4732 - accuracy: 0.8090 - val_loss: 0.4315 - val_accuracy: 0.8172
Epoch 7/10
623/623 [==============================] - 0s 30us/step - loss: 0.4649 - accuracy: 0.

In [ ]:
model.evaluate(X_test,y_test)

In [ ]:
y_test

In [ ]:
score

In [28]:
print('Test loss:', score[0])
print('Test accuracy:', score[1])

NameError: name 'score' is not defined

In [32]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 100)               1100      
_________________________________________________________________
dense_5 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 202       
Total params: 11,402
Trainable params: 11,402
Non-trainable params: 0
_________________________________________________________________
